# AWS EKS Production environment values
environment: prod

# ECR Image Pull Secret
imagePullSecrets:
  - name: ecr-pull-secret

# Tool Server Configuration
toolServer:
  replicaCount: 1

  image:
    repository: 283174975792.dkr.ecr.us-west-2.amazonaws.com/summitlabs/tool-server
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:283174975792:certificate/446317f6-083f-4aac-bfce-269f58e76da6
      alb.ingress.kubernetes.io/tags: Environment=production,ManagedBy=kubernetes,Service=tool-server
    hosts:
      - host: tools.agentstudioapp.com
        paths:
          - path: /
            pathType: Prefix

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  autoscaling:
    enabled: false

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false

  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3

  env:
  # Use AWS Secrets Manager or Kubernetes Secrets in production
  - name: TAVILY_API_KEY
    valueFrom:
      secretKeyRef:
        name: tool-server-secrets
        key: TAVILY_API_KEY
  - name: DISABLE_AUTH
    value: "true"

# LangConnect Configuration
langconnect:
  replicaCount: 1

  image:
    repository: 283174975792.dkr.ecr.us-west-2.amazonaws.com/summitlabs/langconnect
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 8080

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  autoscaling:
    enabled: false

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false

  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3

  env:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: langconnect-secrets
        key: OPENAI_API_KEY
  - name: ALLOW_ORIGINS
    value: '["https://summitlabs.io"]'  # Restrict to production domain
  - name: SUPABASE_URL
    value: "https://iaeptedenfbzhocjolpv.supabase.co"
  - name: SUPABASE_KEY
    valueFrom:
      secretKeyRef:
        name: langconnect-secrets
        key: SUPABASE_KEY

# Web Frontend Configuration
web:
  replicaCount: 1

  image:
    repository: 283174975792.dkr.ecr.us-west-2.amazonaws.com/summitlabs/web
    pullPolicy: Always
    tag: "latest"

  containerPort: 3000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:283174975792:certificate/9bcd76de-f170-4074-ac33-af8e38ebb215
      alb.ingress.kubernetes.io/tags: Environment=production,ManagedBy=kubernetes,Service=web
    hosts:
      - host: agentstudioapp.com
        paths:
          - path: /
            pathType: Prefix

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  autoscaling:
    enabled: false

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false

  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3

  env:
  # Public/Non-sensitive variables
  - name: NEXT_PUBLIC_SITE_URL
    value: "https://agentstudioapp.com"
  - name: NEXT_PUBLIC_PRODUCT_NAME
    value: "Agentstudio"
  - name: NEXT_PUBLIC_SITE_TITLE
    value: "Agent Studio - Your AI Experts"
  - name: NEXT_PUBLIC_DEFAULT_THEME_MODE
    value: "light"
  - name: NEXT_PUBLIC_THEME_COLOR
    value: "#ffffff"
  - name: NEXT_PUBLIC_THEME_COLOR_DARK
    value: "#0a0a0a"
  - name: NEXT_PUBLIC_AUTH_PASSWORD
    value: "true"
  - name: NEXT_PUBLIC_AUTH_MAGIC_LINK
    value: "false"
  - name: NEXT_PUBLIC_CAPTCHA_SITE_KEY
    value: ""
  - name: NEXT_PUBLIC_BILLING_PROVIDER
    value: "stripe"
  - name: CMS_CLIENT
    value: "keystatic"
  - name: NEXT_PUBLIC_KEYSTATIC_CONTENT_PATH
    value: "./content"
  - name: NEXT_PUBLIC_LOCALES_PATH
    value: "apps/web/public/locales"
  - name: NEXT_PUBLIC_ENABLE_THEME_TOGGLE
    value: "true"
  - name: NEXT_PUBLIC_ENABLE_PERSONAL_ACCOUNT_DELETION
    value: "true"
  - name: NEXT_PUBLIC_ENABLE_PERSONAL_ACCOUNT_BILLING
    value: "true"
  - name: NEXT_PUBLIC_ENABLE_TEAM_ACCOUNTS_DELETION
    value: "true"
  - name: NEXT_PUBLIC_ENABLE_TEAM_ACCOUNTS_BILLING
    value: "true"
  - name: NEXT_PUBLIC_ENABLE_TEAM_ACCOUNTS
    value: "true"
  - name: NEXT_PUBLIC_ENABLE_TEAM_ACCOUNTS_CREATION
    value: "true"
  - name: NEXT_PUBLIC_LANGUAGE_PRIORITY
    value: "application"
  - name: NEXT_TELEMETRY_DISABLED
    value: "1"
  - name: NEXT_PUBLIC_SUPABASE_URL
    value: "https://iaeptedenfbzhocjolpv.supabase.co"
  - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhZXB0ZWRlbmZiemhvY2pvbHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTEzMDUsImV4cCI6MjA3MDc4NzMwNX0.7QtYTCTWRI624M7SFaAOVfVr3teRhkE75lMhPqikcLA"
  - name: NEXT_PUBLIC_SUPABASE_PUBLIC_KEY
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhZXB0ZWRlbmZiemhvY2pvbHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTEzMDUsImV4cCI6MjA3MDc4NzMwNX0.7QtYTCTWRI624M7SFaAOVfVr3teRhkE75lMhPqikcLA"
  - name: EMAIL_SENDER
    value: "AgentStudio <smithcp200@gmail.com>"
  - name: EMAIL_PORT
    value: "54325"
  - name: EMAIL_HOST
    value: "localhost"
  - name: EMAIL_TLS
    value: "false"
  - name: EMAIL_USER
    value: "user"
  - name: CONTACT_EMAIL
    value: "test@makerkit.dev"
  - name: MAILER_PROVIDER
    value: "nodemailer"
  - name: DEFAULT_AI_MODEL
    value: "anthropic/claude-3.5-sonnet"
  - name: LANGCONNECT_URL
    value: "http://summitlabs-prod-langconnect:8080"
  - name: NEXT_PUBLIC_LANGGRAPH_API_URL
    value: "http://summitlabs-prod-aegra:8000"
  - name: NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID
    value: "1330eb23-3a7a-4f4e-884f-f09b60c2c6f9"
  - name: NEXT_PUBLIC_LANGGRAPH_MODEL
    value: "openai"
  - name: NEXT_PUBLIC_API_URL
    value: "https://tools.agentstudioapp.com"
  - name: NODE_ENV
    value: "production"
  - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    value: "pk_test_51MuLcqFLcOZkAjiBRVXGkVF5IOx17s2AHWHPV4c5m79iwlbnHl7OUcDL45f7XFJolcCgqAMaswFlL7Vx5y7IfqBH00BCkSa8tW"
  # Sensitive variables from secrets
  - name: SUPABASE_SERVICE_ROLE_KEY
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: SUPABASE_SERVICE_ROLE_KEY
  - name: SUPABASE_DB_WEBHOOK_SECRET
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: SUPABASE_DB_WEBHOOK_SECRET
  - name: EMAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: EMAIL_PASSWORD
  - name: STRIPE_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: STRIPE_SECRET_KEY
  - name: STRIPE_WEBHOOK_SECRET
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: STRIPE_WEBHOOK_SECRET
  - name: OPENROUTER_API_KEY
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: OPENROUTER_API_KEY
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: OPENAI_API_KEY
  - name: LANGCONNECT_API_KEY
    valueFrom:
      secretKeyRef:
        name: web-secrets
        key: LANGCONNECT_API_KEY

# PostgreSQL Configuration
postgres:
  image:
    repository: pgvector/pgvector
    tag: pg16
    pullPolicy: IfNotPresent

  auth:
    username: postgres
    password: CHANGE_ME_IN_PRODUCTION  # Use AWS Secrets Manager
    database: postgres

  persistence:
    enabled: true
    storageClass: "gp3"  # AWS EBS gp3
    accessMode: ReadWriteOnce
    size: 20Gi

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  podSecurityContext:
    fsGroup: 999

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 999

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3

# Redis Configuration
redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379

  persistence:
    enabled: true
    storageClass: "gp3"
    accessMode: ReadWriteOnce
    size: 5Gi

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    fsGroup: 999

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3

# Aegra Configuration
aegra:
  replicaCount: 1

  image:
    repository: 283174975792.dkr.ecr.us-west-2.amazonaws.com/summitlabs/aegra
    pullPolicy: Always
    tag: "latest"

  containerPort: 8000

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:283174975792:certificate/0d774e5e-188d-4019-ab7a-0cdef2555c45
      alb.ingress.kubernetes.io/tags: Environment=production,ManagedBy=kubernetes,Service=aegra
    hosts:
      - host: langgraph.agentstudioapp.com
        paths:
          - path: /
            pathType: Prefix

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  autoscaling:
    enabled: false

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false

  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3

  env:
  - name: DATABASE_URL
    value: "postgresql+asyncpg://postgres:CHANGE_ME_IN_PRODUCTION@summitlabs-prod-postgres:5432/aegra"
  - name: AUTH_TYPE
    value: "noop"
  - name: DEBUG
    value: "false"
  - name: PORT
    value: "8000"
  - name: REDIS_URL
    value: "redis://summitlabs-prod-redis-0.summitlabs-prod-redis:6379"
  - name: TOOL_SERVER_API_KEY
    value: "PLACEHOLDER"
  - name: TOOL_SERVER_URL
    value: "http://summitlabs-prod-tool-server:8000"
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: aegra-secrets
        key: OPENAI_API_KEY

# Service Account
serviceAccount:
  create: true
  annotations:
    # For AWS IAM Roles for Service Accounts (IRSA):
    # eks.amazonaws.com/role-arn: arn:aws:iam::283174975792:role/summitlabs-prod-role
  name: ""

nameOverride: ""
fullnameOverride: ""
