apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: summitlabs-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:smithcp200/helm.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-aws-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: summitlabs-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
