{{- if .Values.aegra.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "summitlabs.fullname" . }}-aegra
  labels:
    {{- include "summitlabs.labels" . | nindent 4 }}
    app.kubernetes.io/component: aegra
  {{- with .Values.aegra.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.aegra.ingress.className }}
  ingressClassName: {{ .Values.aegra.ingress.className }}
  {{- end }}
  {{- if .Values.aegra.ingress.tls }}
  tls:
    {{- range .Values.aegra.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.aegra.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "summitlabs.fullname" $ }}-aegra
                port:
                  number: {{ $.Values.aegra.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
