apiVersion: v1
kind: Service
metadata:
  name: {{ include "summitlabs.fullname" . }}-postgres
  labels:
    {{- include "summitlabs.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "summitlabs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
